name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Build for Web
      run: flutter build web --base-href=/dev-dictionary/

    - name: Build Android APK
      run: flutter build apk

    - name: Build Android App Bundle
      run: flutter build appbundle

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          build/web/
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/flutter-appbundle/app-release.aab
